"""Figure ``fig: cap4ex1`` (JFM-template.tex, ``sec: quartet_rh_gravity``,
``Figures/quartet_rossby_kelvin_panel.png``): Quartet C (RH(4,5)+RH(3,4)+
RH(1,2)+EG(1,1)) at all four modes driven equally at 40 m/s -- a symmetric
IC, not the registry's own default (a=b=c=d=30 m/s), chosen (2026-08-28)
to look for new/lower-frequency periods generated by coupling the RH-only
triad with the Kelvin-like gravity mode EG(1,1).

3x2 grid -- top row: Triad 1 (RH-only, a,b,c), Triad 2 (with EG(1,1),
a,b,d), and the full quartet, each an energy-evolution panel (EG(1,1)
highlighted solid, matching this figure's own prior convention); bottom
row: one novelty-frequency spectrum panel per Rossby mode (RH(4,5),
RH(3,4), RH(1,2)), each comparing the full quartet against whichever
sub-triad(s) contain it. tf_days=200 (vs. the registry's own 20d) --
long enough for `rsw_sphere.utilities.periods._default_xmax`'s own
sqrt(tf_days/2) scaling to show up to 10d, wide enough to resolve the
~4.5d period this configuration turns out to produce (see module-level
numbers printed by ``main()``).

Retires the separate ``fig: power1`` power-spectrum figure (previously
``paper_figure009_quartet_rossby_kelvin_periods.py``, now in
``examples/figures/legacy/``) -- its own spectra are now this figure's
own bottom row instead of a companion figure.

Run:

    python examples/figures/paper_figure008_quartet_rossby_kelvin_panel.py
"""
import dataclasses
import os
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

import matplotlib.pyplot as plt

from rsw_sphere.dynamics.run_config import RunConfig
from rsw_sphere.dynamics.trajectory_cache import _mode_slug
from rsw_sphere.dynamics.diagnostics_report import compute_diagnostics_report
from rsw_sphere.plotting.style import apply_house_style
from rsw_sphere.plotting.labels import _mode_label
from rsw_sphere.plotting.energy_evolution import plot_energy_evolution
from rsw_sphere.plotting.novelty_frequency_panel import novelty_frequency_figure
from rsw_sphere.utilities.novelty_frequency import novelty_combined_for_target

WAVE_SET_KEY = "quartet_rossby_kelvin"
VELOCITIES = (40.0, 40.0, 40.0, 40.0)  # a, b, c, d -- all modes driven equally
TF_DAYS = 200.0
HIGHLIGHT_KEY = "d"  # EG(1,1) -- matches this figure's own prior convention
ROSSBY_LABELS = ["RH(4,5)", "RH(3,4)", "RH(1,2)"]
DEFAULT_OUTPUT = os.path.join(_ROOT, "outputs", "figures", "wave_sets", WAVE_SET_KEY,
                               "paper_figure008_quartet_rossby_kelvin_panel.png")

#: Display-only axis limits (days) -- independent of TF_DAYS/the spectrum's
#: own auto-scaled search window (rsw_sphere.utilities.periods._default_xmax
#: would give sqrt(200/2)=10d here). The full tf_days=200 integration and
#: its full search window are still what's computed; these only crop what's
#: SHOWN, tuned by eye for this one paper figure -- not meant to generalize
#: to run_dynamics.py's own diagnostic figures.
EVOLUTION_XMAX_DAYS = 20.0
SPECTRUM_XMAX_DAYS = 8.0


def compute():
    """Run (cached) the full quartet + both constituent triads at the
    symmetric 40 m/s IC. Returns (spec, results).
    """
    from run_dynamics import run_dynamics
    spec0 = RunConfig.from_registry_entry(WAVE_SET_KEY).wave_set_spec
    spec = dataclasses.replace(spec0, velocities=VELOCITIES)
    config = RunConfig.from_wave_set(spec, tf_days=TF_DAYS, h=0.01, plot=False, parallel=False)
    results = run_dynamics(config)
    return spec, results


def _unit_modes(spec, name: str):
    """(m, n, alpha) tuples for one unit's own modes, in the same order
    as that unit's own r['labels'].
    """
    if name == "full":
        return spec.modes
    for i in range(spec.n_triads()):
        member_p, member_q, _ = spec.sub_triad_modes(i)
        if name == f"triad_{_mode_slug(*member_p)}_{_mode_slug(*member_q)}":
            return spec.sub_triad_modes(i)
    raise ValueError(f"no constituent triad of {spec.key!r} matches unit name {name!r}")


def plot(spec, results, path: str = None,
         evolution_xmax: float = EVOLUTION_XMAX_DAYS, spectrum_xmax: float = SPECTRUM_XMAX_DAYS):
    apply_house_style()
    fig, axes = plt.subplots(2, 3, figsize=(16.5, 9))

    triad_names = []
    for i in range(spec.n_triads()):
        member_p, member_q, _ = spec.sub_triad_modes(i)
        triad_names.append(f"triad_{_mode_slug(*member_p)}_{_mode_slug(*member_q)}")

    highlight_label = _mode_label(*spec.modes[spec.index(HIGHLIGHT_KEY)])
    for ax, name in zip(axes[0, :2], triad_names):
        r = results[name]
        modes = _unit_modes(spec, name)
        highlight = r["labels"].index(highlight_label) if highlight_label in r["labels"] else None
        plot_energy_evolution(r["t"], r["E"], r["E_total"], r["labels"], modes,
                               highlight=highlight, ax=ax)
        ax.set_title(r["title"], fontsize=10)
        ax.set_xlim(0, evolution_xmax)

    r_full = results["full"]
    plot_energy_evolution(r_full["t"], r_full["E"], r_full["E_total"], r_full["labels"],
                           _unit_modes(spec, "full"),
                           highlight=r_full["labels"].index(highlight_label),
                           ax=axes[0, 2])
    axes[0, 2].set_title(spec.display_label, fontsize=10)
    axes[0, 2].set_xlim(0, evolution_xmax)

    for ax, label in zip(axes[1], ROSSBY_LABELS):
        novelty_result = novelty_combined_for_target(results, label)
        novelty_frequency_figure(results, label, novelty_result, ax=ax, xmax=spectrum_xmax)
        ax.set_title(f"Spectrum: {label}", fontsize=10)

    # Every panel in a row shares the same y-axis meaning -- only the
    # leftmost of each row needs the label.
    for ax in list(axes[0, 1:]) + list(axes[1, 1:]):
        ax.set_ylabel("")

    fig.tight_layout()
    if path:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        fig.savefig(path, dpi=200, bbox_inches="tight")
        plt.close(fig)
    else:
        plt.show()


def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", nargs="?", default=DEFAULT_OUTPUT)
    parser.add_argument("--evolution-xmax", type=float, default=EVOLUTION_XMAX_DAYS,
                         help="days shown on the top row's time axis (display only, "
                              "tuned by eye -- doesn't affect the tf_days=200 integration)")
    parser.add_argument("--spectrum-xmax", type=float, default=SPECTRUM_XMAX_DAYS,
                         help="days shown on the bottom row's period axis (display only)")
    args = parser.parse_args()

    spec, results = compute()
    plot(spec, results, path=args.path,
         evolution_xmax=args.evolution_xmax, spectrum_xmax=args.spectrum_xmax)
    print(f"wrote {os.path.abspath(args.path)}")

    report = compute_diagnostics_report(results, spec)
    print("\n=== per-unit dominant period, Rossby modes ===")
    for label in ROSSBY_LABELS:
        for name in results:
            if label not in results[name]["labels"]:
                continue
            m = report["per_mode_unit"][name][label]
            print(f"  [{name}] {label}: period_global={m['period_global']:.4f}d")

    print("\n=== final (combined) diagnostics, Rossby modes ===")
    for label in ROSSBY_LABELS:
        d = next(d for d in report["final"] if d["mode"] == label)
        print(f"  {label}: p_measure={d['p_measure_final_pct']:+.2f}%  "
              f"spectral_dev={d['spectral_dev_final_pct']:.2f}%  vs={d['vs']}  "
              f"novelty_period={d['novelty_period_final_days']:.4f}d "
              f"({d['novelty_relevance_final_pct']:.2f}%)")


if __name__ == "__main__":
    main()
